---
kind: pipeline
type: docker
name: alarm-aarch64

platform:
  os: linux
  arch: arm64

node:
  qemu: no

steps:
  - name: build-image
    image: plugins/docker
    environment:
      TZ: Europe/Rome
    settings:
      dockerfile: Dockerfile.aarch64
      purge: true
      username: depau
      password:
        from_secret: docker_password
      repo: depau/archlinux-daily
      tags:
        - aarch64

---
kind: pipeline
type: docker
name: archlinux-x86_64

platform:
  os: linux
  arch: amd64

node:
  qemu: no

steps:
  - name: build-image
    image: plugins/docker
    environment:
      TZ: Europe/Rome
    settings:
      dockerfile: Dockerfile.x86_64
      purge: true
      username: depau
      password:
        from_secret: docker_password
      repo: depau/archlinux-daily
      tags:
        - x86_64
